name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Evitar builds concurrentes
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Instalar dependencias
      run: npm ci
      
    - name: Verificar tipos TypeScript
      run: npm run build --dry-run || npx tsc --noEmit
      
    - name: Build del proyecto
      run: npm run build
      
    - name: Verificar archivos de build
      run: |
        echo "Verificando archivos generados..."
        ls -la dist/
        if [ ! -f "dist/index.html" ]; then
          echo "Error: index.html no encontrado en dist/"
          exit 1
        fi
        echo "Build exitoso ✅"
        
    - name: Upload build artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  # Job de deploy (solo en push a main)
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Deploy a GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
